tap "1password/tap"
tap "azure/functions"
tap "buo/cask-upgrade"
tap "grishka/grishka" # for NearDrop
tap "hashicorp/tap"
tap "homebrew/bundle"
tap "homebrew/services"
tap "qmk/qmk"
brew "act"
brew "azure-cli"
brew "git"
brew "hashicorp/tap/terraform", link: false
brew "jq"
brew "mackup"
brew "mas"
brew "maven"
brew "mysql"
brew "nginx"
brew "nmap"
brew "node"
brew "node@16"
brew "openjdk"
brew "openshift-cli"
brew "python@3.12"
brew "qmk/qmk/qmk"
brew "rcm"
brew "telnet"
brew "terraform-docs"
brew "tfenv"
brew "wget"
brew "yj"
cask "1password-cli"
cask "1password"
cask "brave-browser"
cask "coconutbattery"
cask "docker"
cask "dozer"
cask "drawio"
cask "font-fira-code"
cask "font-ibm-plex-sans-thai-looped"
cask "font-ibm-plex-sans-thai"
cask "font-ibm-plex-sans"
cask "font-meslo-lg-nerd-font"
cask "github"
cask "iterm2"
cask "localsend"
cask "logi-options+"
cask "macfuse"
cask "mullvadvpn"
cask "neardrop"
cask "pgadmin4"
cask "postman"
cask "progressive-downloader"
cask "qmk-toolbox"
cask "qmk-toolbox"
cask "raycast"
cask "smooze-pro"
cask "soundsource"
cask "spotify"
cask "visual-studio-code"
cask "vlc"
cask "zenmap"
cask "zoom"
mas "1Password for Safari", id: 1569813296
mas "Amphetamine", id: 937984704
mas "Balance Lock", id: 1019371109
mas "Brother iPrint&Scan", id: 1193539993
mas "Goodnotes", id: 1444383602
mas "LINE", id: 539883307
mas "Magnet", id: 441258766
mas "rcmd", id: 1596283165
mas "RunCat", id: 1429033973
mas "Sequel Ace", id: 1518036000
mas "The Unarchiver", id: 425424353
mas "Time Out", id: 402592703